### ISSUE TITLE
Please review translation.js code

### ISSUE THREAD

**Issue by Helkyd** [frappe/frappejs#163]
Found # and is returning error

 #translate(segment) {
    // TODO: implement translation backend
    return segment;
  }

  #stitch() {
    if (typeof this.args[0] === 'string') {
      return stringReplace(this.args[0], this.args.slice(1));
    }

**Comment by 18alantom** [comment]
Yup, I realised it when I  restarted `yarn electron:serve`. For whatever reason, it was working when I made the changes whilst `yarn electron:serve` was running.

The issue seems to be some kinda bug that is preventing `babel-loader` from being used for transpiling the dependencies.

Due to this and other reasons, I'll be inlining `frappejs` code into `books` (the relevant parts): https://github.com/frappe/books/pull/320

**Comment by 18alantom** [comment]
Closing this cause: https://github.com/frappe/frappejs/issues/164
